In [2]:
import numpy as np


arr1 = np.arange(1, 21, 3)
print("Task 1 - Array with increment of 3:")
print(arr1)


arr2 = np.random.rand(3, 3)
print("\nTask 2 - Random 3x3 array:")
print(arr2)


arr3 = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print("\nTask 3 - 2D Array:")
print(arr3)


first_two_rows = arr3[:2, :]
print("\nSliced first two rows:")
print(first_two_rows)


last_two_rows = arr3[1:, :]
print("\nSliced last two rows:")
print(last_two_rows)

arr4a = np.array([[1, 2], [3, 4]])
arr4b = np.array([[5, 6], [7, 8]])

stacked_vertically = np.vstack((arr4a, arr4b))
print("\nStacked Vertically:")
print(stacked_vertically)

stacked_horizontally = np.hstack((arr4a, arr4b))
print("\nStacked Horizontally:")
print(stacked_horizontally)

split_vertically = np.vsplit(stacked_vertically, 2)
print("\nSplit Vertically:")
print(split_vertically)

split_horizontally = np.hsplit(stacked_horizontally, 2)
print("\nSplit Horizontally:")
print(split_horizontally)

X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

if X.shape[1] == Y.shape[0]:
    result = np.dot(X, Y)
    print("\nMatrix Multiplication Result:")
    print(result)
else:
    print("\nMatrix multiplication is not possible due to shape mismatch.")

x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

shape_x = x.shape
dim_x = x.ndim
print("\nTask 6 - Shape and Dimensions of vector x:")
print("Shape:", shape_x)
print("Dimensions:", dim_x)

x_reshaped = x.reshape((3, 1))
y_reshaped = y.reshape((3, 1))
dim_x_reshaped = x_reshaped.ndim

print("\nReshaped x to (3, 1):")
print(x_reshaped)
print("Dimensions after reshaping x:", dim_x_reshaped)

dim_y_reshaped = y_reshaped.ndim
print("\nReshaped y to (3, 1):")
print(y_reshaped)
print("Dimensions after reshaping y:", dim_y_reshaped)


matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([10, 20, 30])

result_broadcast = matrix - vector
print("\nTask 7 - Broadcasting:")
print("Matrix:")
print(matrix)
print("Vector:")
print(vector)
print("Result of Matrix - Vector:")
print(result_broadcast)


Task 1 - Array with increment of 3:
[ 1  4  7 10 13 16 19]

Task 2 - Random 3x3 array:
[[0.36638066 0.66072046 0.98045979]
 [0.29558493 0.78254749 0.39799785]
 [0.67895624 0.36378278 0.84069389]]

Task 3 - 2D Array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]

Sliced first two rows:
[[10 20 45]
 [30 12 16]]

Sliced last two rows:
[[30 12 16]
 [42 17 56]]

Stacked Vertically:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Stacked Horizontally:
[[1 2 5 6]
 [3 4 7 8]]

Split Vertically:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]

Split Horizontally:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]

Matrix Multiplication Result:
[[70 28]
 [70 30]
 [60 26]]

Task 6 - Shape and Dimensions of vector x:
Shape: (3,)
Dimensions: 1

Reshaped x to (3, 1):
[[ 2]
 [-1]
 [-8]]
Dimensions after reshaping x: 2

Reshaped y to (3, 1):
[[ 3]
 [ 1]
 [-2]]
Dimensions after reshaping y: 2

Task 7 - Broadcasting:
Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector:
[10 20 30]
Result of Matrix - Vector:
[

In [3]:
import numpy as np

A = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])

b = np.array([10, -4, 6])

try:
    x = np.linalg.solve(A, b)
    print("Part B.1 - Solution for x, y, z:")
    print(x)
except np.linalg.LinAlgError:
    print("Part B.1 - The system is singular and cannot be solved.")


Part B.1 - Solution for x, y, z:
[ 1.8  2.4 -0.2]


In [4]:

A = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])

b = np.array([10, 20, 3, -1])

try:
    x = np.linalg.solve(A, b)
    print("\nPart B.2 - Solution for x, y, z, w:")
    print(x)
except np.linalg.LinAlgError:
    print("\nPart B.2 - The system is singular and cannot be solved.")



Part B.2 - The system is singular and cannot be solved.
